name: Build and Release

on:
  push:
    tags:
      - 'v*' # Se activa al subir tags como v1.3.1, v1.4.0, etc.

permissions:
  contents: write # Otorga permisos para crear el Release en GitHub

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/checkout@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install RPM packaging dependencies
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: Build and Publish Electron App
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist -- --publish always
